version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - mysql-db
    environment:
      DB_HOST: mysql-db
      DB_USER: root
      DB_PASSWORD: qwerty
      DB_NAME: testdb

  mysql-db:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: qwerty
      MYSQL_DATABASE: testdb
    ports:
      - "3306:3306"
    volumes:
      - /data:/var/lib/mysql
